So sorry these commits are not in stages
mattbrailsford/umbraco-authu pull request #38
Opened 2019-05-06 00:36 UTC by marccameron3d

Would love to talk it over with you if you get the time Matt, upgraded to allow for umbraco 8 using the new migration... technique?

I can only apply this PR to the `develop` branch but maybe good to have a v8 version unless the previous nuget builds are fine to live as they are.

Initially the framework needed updates to 4.7.2 to allow for the new UmbracoCMS.Core

**Updating Nugets:**
UmbracoCms.core version - 8.0+
Microsoft.AspNet.WebApi.WebHost - 5.2.7.0

After this, the next step was converting over how the code access's the database using the new `Composer.Current...`

Once this was complete you are able to run the `/oauth/token` endpoint successfully once you initialise the `OAuth.ConfigureEndpoint("/oauth/token", ...` method within a `IComponent` and register it using the `IUserComposer`.

This was the easy bit, although this was not able to use refresh token store or client store.

So I have removed the old migration runner and updated to use the new practice adopted by umbraco v8, which was good to learn. I have built 2 plans and included a helper to pull the state from the db. As it doesnt support Up / Down anymore I have included a remove as well as the initialise migrations.

I didnt expect to get where I was so happy to go over it and take some pointers from you about the code. Hope its useful for you, I will be using it actively in my current project and havent encountered any issues as of yet.

It could maybe do with a clean up or discussion over versioning the states as I know you used semver before, so it can either be removed now or states amended to use it.

2019-05-07 09:02 UTC, mattbrailsford commented
Hey Marc,

This is awesome. I haven't looked through it all yet so I'll get back to you as soon as I can with feedback, but just wanted to say a big thank you in the meantime.

Matt

2019-06-20 18:52 UTC, mattbrailsford requested changes
Hey Marc, sorry for the delay on this.

It's a really good first stab at an update, so thanks for putting in the time to do this. I've just raised a few things to look into. Feel free to ping me if you want to go through anything.

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Component/MigrationsRunnerComponent.cs
> +                //var upgrader = new Upgrader(new RemoveOAuthTables());
To be honest, I don't think we need to worry about downgrading. Umbraco have removed the ability to undo a migration, so I'd say lets just focus on installing.

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Data/Migrations/UmbracoDbOAuthClientStore/Remove/DeleteAuthClientStoreTable.cs
> +﻿using Our.Umbraco.AuthU.Models;
Doing away with the downgrader, this won't be needed

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Data/Migrations/UmbracoDbOAuthClientStore/Add/CreateAuthClientStoreTable.cs
> +﻿using Our.Umbraco.AuthU.Models;
These files don't need to be an an Add folder.

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Data/Migrations/UmbracoDbOAuthClientStore/Add/CreateDemoClient.cs
> +		{ }
Formatting appears to be a bit off here. Double check tabs vs spaces.

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Data/Migrations/UmbracoDbOAuthClientStore/Add/CreateDemoClient.cs
> +            var existing = Database.SingleOrDefault<OAuthClient>($"SELECT * FROM [OAuthClient] WHERE [ClientId] = @0", "DemoClient");
I'd probably change this query to `SELECT 1 FROM` as we don't actually need any data, we are just checking if anything exists. Fetching all the data from the DB is a waste here so lets make this as slim as we can.

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Data/Migrations/UmbracoDbOAuthClientStore/Remove/DeleteAuthClientStoreTable.cs
> +		{ }
Formatting

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Data/Migrations/UmbracoDbOAuthRefreshTokenStore/Add/AddDeviceIdColumn.cs
> +		{ }
Formatting

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Data/Migrations/UmbracoDbOAuthRefreshTokenStore/Add/AddDeviceIdColumn.cs
> +            {
For consistency, we should either do away with the curly brackets, or make sure we use curly brackets everywhere. My usual rule is, if it's a one line statement, then don't use them.

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Data/Migrations/UmbracoDbOAuthRefreshTokenStore/Remove/DeleteAuthRefreshTokenStoreTable.cs
> +﻿using Our.Umbraco.AuthU.Models;
Not needed

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Data/Plans/RegisterOAuthTables.cs
> +        public override string InitialState => AuthUKeyValueHelper.GetValue();
I don't think this is quite right. I don't think you want to be looking up the current state from the DB, rather I think this is more for when you are upgrading from like v7. Given our install scripts are defensive, only applying when needed, I think we might be able to just have this as an empty string.

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Data/Plans/RemoveOAuthTables.cs
> +﻿using Our.Umbraco.AuthU.Data.Helpers;
Not needed

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Data/UmbracoDbOAuthClientStore.cs
> +		protected Database Db => new Database("umbracoDbDsn");
Should be reusing the DB from the umbraco database context like it was before.

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Data/UmbracoDbOAuthRefreshTokenStore.cs
> +        protected Database Db => new Database("umbracoDbDsn");
Reuse umbraco database

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Extensions/StringExtensions.cs
> +        internal static string oAuthGenerateHash(this string input)
I'd probably rename this be be more natural, ie `GenerateOAuthHash`

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Data/Plans/RegisterOAuthTables.cs
> +                From(InitialState)
Duplication here, but given the above comment, I think we only need one route anyway.

2019-06-20 18:52 UTC, mattbrailsford commented on src/Our.Umbraco.AuthU/Data/Plans/RegisterOAuthTables.cs
> +        public RegisterOAuthTables(bool CreateDemoClient = false) : base("AuthU")
`CreateDemoClient` is never true. I think we could probably just remove this param and just always install demo client. If people don't use it, it's not a big deal.

2019-07-07 21:43 UTC, marccameron3d commented
Ill change the DB context to use IScopeProvider, unless you know of a better way? I think registering this as a difference service may be good so we can use it in the AuthClientStore and RefreshTokenStore without the need to add the param to the constructor of each when calling them?

2019-07-08 19:46 UTC, marccameron3d reviewed
I have updated the comments you mentioned, my concern is with the database context and if using Current is the best way?

2019-08-19 14:30 UTC, marccameron3d commented
@qz2rg4 Hey mate, the changes I have implemented on this PR work for me on a prod project. There is one ailment I found relating to header being set twice for CORS but I can add that issue in. The changes are failing to build but @mattbrailsford will review when he has time. In the meanwhile happy to help you out if you need it. @marcD8 is an old account from a previous role so hit me up on @marccameron3d

2019-10-26 10:44 UTC, merged